### PR TITLE
Updated MEF3 reader and Updated MEF2.1 reader

### PR DESCRIPTION
**Pull request by MaxvandenBoom**
Hi Richard,

I've updated the MEF3 reader in this PR. After accepting, you might still need to update the references in your code that refer to `read_mef_header_mex_3p0`, since `read_mef_session_metadata` now includes the file-header. Let me know if you need anything else in that regard which is EEGLab specific.

I will check the compiling of MEF2.1 in Windows, and if needed send a separate pull request to solve.

Best,
Max

### CODE REVIEW

**Comment by jiecui** [comment]
Thanks a lot, max! I'll try to find a time to work on it soon.

**Comment by MaxvandenBoom** [comment]
Hey Richard,

I fixed the MEF2.1 reader as well and updated it in this same pull-request.

The MEF2.1 had a number of deprecated, legacy or one-compiler-specific calls. I've updated the most important bits to make it work with more compilers. I recompiled and tested `read_mef_header_2p1` and `decompress_mef_2p1` both on Mac and Windows, they work perfectly on the MEF2.1 example data that is in the package. I also included the updated mac and new windows mex-binaries in the package.

Keep me posted! :)

**Comment by jiecui** [comment]
merged manually. Thanks, Max!

**Comment by jiecui** [comment]
Reverted and merged PR on GitHub.

**Comment by MaxvandenBoom** [comment]
Nice, thank you Richard!

**Pull request merged**
